settings:
  APP_DISPLAY_NAME: Element X
  PRODUCTION_APP_NAME: Element
  APP_GROUP_IDENTIFIER: group.halalz.io.elementx
  BASE_BUNDLE_IDENTIFIER: halalz.io.elementx
  ASSETCATALOG_COMPILER_GLOBAL_ACCENT_COLOR_NAME: "colors/accent-color"
  DEVELOPMENT_TEAM: 2DVSJM88ZU
